server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: orders-ms
              uri: lb://orders-ms
              predicates:
                - Path=/pedidos,/pedidos/**
            - id: payment-ms
              uri: lb://payment-ms
              predicates:
                - Path=/payments,/payments/**